### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by ziccardi**
## Motivation

Our projects are using a hybrid approach on managing dependencies.
Some project is using the package.config file to enlist the dependencies (the old, deprecated way) and some other project is using PackageReference inside the csproj (the new suggested way).

This is creating some issue because we are getting some dependency issue.

This PR switches all the projects to the new format.

Moreover, there were cases of dependencies repeated more than one time in the same project. Sometimes even with different versions. That leads to weird issues. 
Hopefully with this new structure that should not happen anymore.

### CODE REVIEW

**Comment by wei-lee** [comment]
looks like the dependencies installed fine, but the ios project can not be built.

**Comment by ziccardi** [comment]
@wei-lee : yes, that's the issue with appveyor building the Example app. Building locally it works. I think we should discuss about this 'submodule' solution we are currently using.

**Comment by secondsun** [comment]
@wojta It looks like the Example.iOS project is being pulled into the configuration even though it isn't in the config for https://github.com/aerogear/aerogear-xamarin-sdk/pull/69

You can check in both build logs.  IN #69 you see the message that example.ios is not included, but no message is included in this PR's build.  However Android is excluded still.

**Comment by ziccardi** [comment]
@wojta 
Example uses the same version as all the other projects: 2.x. 
Look here:

- [Example](https://github.com/aerogear/xamarin-showcase-template/blob/master/Example/Example.csproj#L19)
- [Example.iOS](https://github.com/aerogear/xamarin-showcase-template/blob/master/Example.iOS/Example.iOS.csproj#L168)
- [Example.Android](https://github.com/aerogear/xamarin-showcase-template/blob/master/Example.Android/Example.Android.csproj#L86)

I think the problem about example is that VS/MSbuild is caching the Xamarin.Forms somewhere.

**Comment by wojta** [comment]
@ziccardi It's still using 3.x 
https://github.com/aerogear/xamarin-showcase-template/blob/17ceec2747c1dd7531505f46e56b17efcdcb827f/Example.iOS/Example.iOS.csproj#L168
You'll need to update the submodule to 25a117d .

**Comment by ziccardi** [comment]
@wojta : good catch! showcase master was pointing to version 2.5, but the submodule was not updated (was pointing to an old commit). I updated it.

@secondsun : I fixed the AppVeyor config in the solution. The Example.iOS was not excluded.

**Pull request merged**
