### PR TITLE
Ziccardi aerogear 2450

### PR DESCRIPTION
**Pull request by wei-lee**
## Motivation

Replace PR #13 

## Description

* Add new classes for User and Role
* Update the Auth project to use .NET standard (1.3)

### CODE REVIEW

**Comment by wei-lee** [comment]
ping @aidenkeating @wojta mind taking a look?

I think we should try targeting the lowest .NET standard version possible. This will allow us to support more platforms.

**Comment by wojta** [comment]
I think that we should stick with .NET Standard 2.0. On Android we are also targetting latest SDKs. Also by the time of anybody using this in their project it will be quite common. 
Even UWP supports this now.

**Comment by wei-lee** [comment]
@wojta Ideally if we only need to support new project, then that will be great. But I think we also need to consider the fact that we want to support some customers who may have an existing project already.

According to this doc: https://docs.microsoft.com/en-gb/dotnet/core/tutorials/libraries fro Microsoft, it is recommended to target .Net standard 1.4 for most of the projects, as it provides a good balance between API availability and platform support. So I think we will use that instead.

In the future, if there is some specific .NET standard 2.0 APIs we need to use, we can come back and review the target versions.

WDYT?

**Comment by wojta** [comment]
LGTM, btw. I think we should also change Core.Tests to .Net Core 2.0.Oor not?

**Comment by wei-lee** [comment]
@wojta sounds good. I will do that as well.

**Comment by wei-lee** [comment]
@wojta actually, can't change Core.Tests project to a .NET core project, as the one of the dependencies (WireMock) is not available for .NET core.

Maybe we should change the Auth.Tests to a .NET framework project later on. But for now, let's leave them as they are.

**Pull request merged**
