### PR TITLE
Adding token refresh functionality (porting android code)

### PR DESCRIPTION
**Pull request by ziccardi**
## Motivation
Token Refresh Functionality 
JIRA: https://issues.jboss.org/browse/AEROGEAR-7908

**Tasks**:

- [x] Implement refresh token for Android
- [x] Implement refresh token for iOS
- [x] Add comments

### Changes

- Added a CurrentUser(bool autoRefresh) method to the AuthService class, so that, when asking for the current user, the caller can choose if automatically refresh the token (if needed) or not. This method is `asynchronous` on both iOS and Android
- Added the AuthHeaderProvider class in the shared code
- Added a `TokenLifecycleManager` class to the shared code. This class implements the common part of the refresh feature.
- Added an extension to the `TokenLifecycleManager` class in both the Android and the iOS project to add platform specific features.

### CODE REVIEW

**Comment by ziccardi** [comment]
ping @wojta @secondsun

**Comment by secondsun** [comment]
@ziccardi I'll look at it for Android today.  Do we have someone who can check iOS?

**Comment by ziccardi** [comment]
@secondsun Maybe @wojta ?

**Comment by ziccardi** [comment]
@wojta : mind verifying on iOS?

**Pull request merged**
