### PR TITLE
Added Security Checks metrics

### PR DESCRIPTION
**Pull request by ziccardi**
## Motivation

JIRA: https://issues.jboss.org/browse/AEROGEAR-2872

## Description

- Changed metrics interface to return JsonValue instead of JsonObject
- Added the new SecurityCheckMetric class
- Integrated metrics with the executor
- Renamed `Data` to `ToJson`
## Progress

- [x] Add SecurityCheckMetrics to the executor(s)

### CODE REVIEW

**Comment by secondsun** [comment]
Can I get some verification instructions?  I pulled the PR, updated the Example submodule, and ran the app.  I went to all of the metrics screens and the device checks screen, but nothing ever sent to the services.

**Comment by secondsun** [comment]
image

**Comment by secondsun** [comment]
I was able to verify this so the code works.

I'm wondering if we want to add a "metrics configured" check to the security service.  Right now in Android and this code we have to build the executor itself in the device check screen if we want to use metrics.  It might be interesting if we can make the security service send metrics on its own.

**Comment by ziccardi** [comment]
@secondsun : this should be used together with this https://github.com/aerogear/xamarin-showcase-template/pull/23.
However if PR23 is merged, the showcase won't work anymore until a new SDK version is published and the version used by the showcase is updated.

**Pull request merged**
