### PR TITLE
MOBDOC-14 Add Antora structure to xamarin repo for docs

### PR DESCRIPTION
**Pull request by finp**
## Motivation

Add antora structure to sdk for docs

JIRA: https://issues.jboss.org/browse/MOBDOC-14

### CODE REVIEW

**Comment by wei-lee** [comment]
The changes look fine. Any particular instructions on how to verify the changes?

**Comment by finp** [comment]
@wei-lee  I have some instructions at http://shiftgear.org/processes/latest/docs/antora.html
but  dunno if that helps

**Comment by wei-lee** [comment]
I followed the instructions and looks like it is working. Although I noticed that this is creating a new `docs` dir, even though there is already a `Documentations` dir in the SDK already. Is that necessary?

**Comment by finp** [comment]
@wei-lee could I suggest that we have a follow on task, to convert the existing doc from markdown to asciidoc and include it in the docs directory?

**Comment by finp** [comment]
@wei-lee  btw you could assign that follow on task to me ;) We could reuse documentation directory, but would make this repo different from all the others, that's what i'm trying to avoid

**Comment by wei-lee** [comment]
@finp we have a [task this sprint](https://issues.jboss.org/browse/AEROGEAR-2510) to actually starting on writing the docs. I think we can progress the follow on task as part of that issue. Are you ok with that?

**Comment by finp** [comment]
@wei-lee  perfect

**Comment by wei-lee** [comment]
@finp I have updated the description of the JIRA issue to include the follow on tasks you have mentioned.

**Comment by StephenCoady** [comment]
@wei-lee @finp by the sounds of it this is done. can we merge it?

**Comment by wei-lee** [comment]
@StephenCoady I am ok to merge this if @finp is happy with it.

**Pull request merged**
