### PR TITLE
[WIP] AEROGEAR-2449 Credential Storage Interfaces

### PR DESCRIPTION
**Pull request by aidenkeating**
JIRA: https://issues.jboss.org/browse/AEROGEAR-2449

We need interfaces in order to store credentials.

The implementations of these interfaces will be platform specific and done in other PRs.

First Xamarin PR so it may be missing stuff/way off.

### CODE REVIEW

**Comment by wojta** [comment]
Maybe we can have some ordinary implementation for key-value storage. I think like Android SharedPreferences and iOS UserDefaults. It can be used for more stuff than Auth. Not sure if it should be part of this PR.

**Comment by aidenkeating** [comment]
@wojta So you mean a general `storage` module instead of one just for credentials? If so, I don't see a problem with that. I'd guess that'd live in Core instead of Auth? Any ideas on the interface it would store instead of `ICredential`? I'm not too familiar with Xamarin stuff yet

**Comment by aidenkeating** [comment]
@ziccardi Mind taking a look?

**Comment by wei-lee** [comment]
@aidenkeating I think @wojta is right. The interface should be a general persisted key-value store interface, it doesn't have be limited for credentials. I think we should move them to the core module if they become a general interface.

**Comment by ziccardi** [comment]
@aidenkeating @wojta @wei-lee I think the `ICredentialManager` should work only with `ICredential` objects. We can, of course, make the concrete implementation rely on a generic key-value storing object, but I think we should keep this as well.

**Comment by aidenkeating** [comment]
@wei-lee @ziccardi So would the general key value interface look something like this?

```
    public interface IStorageManager<T>
    {
        void Save(string key, T value);
        T Read(string key);
        void Remove(string key);
        void Clear();
    }
```

After that we could either define a `ICredentialManager` in Auth that uses this interface for `ICredential`. Does that seem like a sane way to go?

**Comment by wei-lee** [comment]
@aidenkeating yes, that sounds good. The generic interface should be part of the core module, and the ICredential one can be used for auth module. It will also allow us to encrypt/decrypt the data if we want to to save the data securely.

**Comment by aidenkeating** [comment]
Closing for https://github.com/aerogear/aerogear-xamarin-sdk/pull/10

**Pull request closed without merging**
